### ISSUE TITLE
Feature : Load data from file

### ISSUE THREAD

**Issue by vinchauhan** [opensource9ja/danfojs#44]
As of now we can only load from https:// urls , I tried http, reading the json file and passing to the method and none of them worked.

It would be great to add reading from file or http urls too.

**Comment by vinchauhan** [comment]
So looks like the issue is with using source as a file name either relative or absolute. I couldn't make it work.

```
dfd.read_json("mini.json")
.then(df => {
    console.log(df);
})
```

df comes as undefined.

**Comment by risenW** [comment]
read_json didn't support local files before, but this has been fixed in the latest [push](https://github.com/opensource9ja/danfojs/blob/6036e0d79637e3fdf00713576cb66e0673cba21e/danfojs/src/io/reader.js#L59). If you are using this in a node environment, you can Install the latest push and test it out.
