### ISSUE TITLE
some DataFrame/Series methods not support level,fill_value etc arguments

### ISSUE THREAD

**Issue by alexwenbj** [opensource9ja/danfojs#48]
For example,DataFrame.mul()/rmul()/sub()... only accept 2 arguments, but in pandas, there are level,fill_value etc.

**Comment by risenW** [comment]
@alexwenbj For now, we try to make methods as simple as possible, so definitely not all features available in pandas are currently supported. Going forward, we can extend these functions to include more options as well.

For instance, fill_value can be the same across all math ops function, so that can be easily added. Other features will be based on importance and request.

**Comment by alexwenbj** [comment]
@risenW Got it.Thank you.
