### ISSUE TITLE
[read_csv] support File object in browser

### ISSUE THREAD

**Issue by pckhoi** [opensource9ja/danfojs#61]
I use `read_csv` to read a 130MB file in the browser and using developer tools I saw the file get downloaded twice, then it just hang and eventually crash. So clearly there is one or two bugs there.

And it would be nice if `read_csv` accept File object in the browser as well.

**Comment by pckhoi** [comment]
I think I understand the double download issue now. First download happened at
```javascript
const column_names = await csvDataset.columnNames()
```

Then second:
```javascript
await sample.forEachAsync(row => data.push(Object.values(row)))
```

Doesn't look very optimized.

**Comment by risenW** [comment]
Thanks for noticing this. We are planning to change the underlying functions for reading CSV files. Currently we are using tfjs read csv function. The latest ode version introduces a generic read function for reading many tabular files. Although still in testing, we will definitely fix this in the next couple of days

**Comment by Devwulf** [comment]
Any updates on this? I would love to have File object support for `read_csv`, especially for browsers. Selecting files using the `<input ...` tag returns File objects, but the `read_csv` currently only takes in a `filePath`, which doesn't make much sense for browsers. This requires the file to first be uploaded somewhere in the cloud before being able to use it for Danfo, making this feature unusable for offline web apps.

Furthermore, PapaParse already supports parsing `.csv` files from File objects, as documented [here](https://www.papaparse.com/docs#local-files), so the fix for this should be fairly easy to implement.

**Comment by risenW** [comment]
> Any updates on this? I would love to have File object support for `read_csv`, especially for browsers. Selecting files using the `<input ...` tag returns File objects, but the `read_csv` currently only takes in a `filePath`, which doesn't make much sense for browsers. This requires the file to first be uploaded somewhere in the cloud before being able to use it for Danfo, making this feature unusable for offline web apps.
> 
> Furthermore, PapaParse already supports parsing `.csv` files from File objects, as documented [here](https://www.papaparse.com/docs#local-files), so the fix for this should be fairly easy to implement.

Hey @Devwulf , the latest version of Danfojs supports file object. See https://danfo.jsdata.org/api-reference/input-output/danfo.read_csv

**Comment by Devwulf** [comment]
> Hey @Devwulf , the latest version of Danfojs supports file object. See https://danfo.jsdata.org/api-reference/input-output/danfo.read_csv

That's weird. I do have the latest version of Danfojs from npm, which is currently `0.3.3`. Is that not the latest version?
