### ISSUE TITLE
Roadmap for `to_csv`?

### ISSUE THREAD

**Issue by GantMan** [opensource9ja/danfojs#64]
I'm having some issues when I get to requiring TensorFlow.js, see #63 

I could work around this if I could save the data to a CSV or JSON.  Is there a roadmap for [making the Pandas to_csv](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html)?

**Comment by risenW** [comment]
There's a current [to_csv](https://danfo.jsdata.org/api-reference/dataframe/dataframe.to_csv) function for that, the only difference, for now, is that we return converted CSV as a string, instead of saving to a path. 

This functionality can be added in node environment since we have access to the file system.

What other features would like to see in this?

**Comment by GantMan** [comment]
Ahhh, I guess just getting it documented in the API reference.  Would you like me to do a PR over here to document it?

https://danfo.jsdata.org/api-reference/input-output

**Comment by risenW** [comment]
Sure, we'd love that. 👍

**Comment by GantMan** [comment]
Done:  https://github.com/opensource9ja/danfojs-doc/pull/2
