### ISSUE TITLE
Missing Intellisense in .ts files?

### ISSUE THREAD

**Issue by davidrint** [opensource9ja/danfojs#73]
Hi Simple question I hope. I get intellisense when using danfojs-node in require in js file. This does not happen in Typescript file. Are you looking to provide npm install @types/danfojs  or is there a way around this.

Looking forward to using the product. Regards David

**Comment by Nenino2** [comment]
I auto-generated Danfojs's types and I put them into my [repository](https://github.com/Nenino2/Danfojs-type-declarations)

You can install them using
```
npm i https://github.com/Nenino2/Danfojs-type-declarations.git -D
``` 

![Screenshot](https://user-images.githubusercontent.com/42894888/103276762-bd689780-49c7-11eb-95c1-22d6bf90423a.png)

**Comment by risenW** [comment]
@Nenino2 Thanks for providing this!

**Comment by davidrint** [comment]
That's great, I will try it tomorrow.  Many thanks

**Comment by risenW** [comment]
@davidrint I have just included the types defined by @Nenino2 in the latest build of danfo. So update your version number.

**Comment by PascalStehling** [comment]
When I try using React with typsecript and danfojs I allwys get the error "Module not found: Can't resolve 'danfojs/danfojs/types/core/frame'" when trying to import danfojs. When using React with Javascript everything is fine, just with Typescript the Error occures.

I allso tried the Generated files from Nenino2, but an similar error occured.

I just changed my used App.tsx, the rest is the standard React Typescript App that you can Generate with `npx create-react-app testapp --template typescript`. Does anybody know where the Problem is or what I can do to fix this?

App.tsx (from the react example, just the import was changed):
```
import React from 'react';
import "./App.css";
import { DataFrame } from 'danfojs/danfojs/types/core/frame';

function App() {

  const df = new DataFrame(
    { pig: [20, 18, 489, 675, 1776], horse: [4, 25, 281, 600, 1900] },
    { index: [1990, 1997, 2003, 2009, 2014] }
  );
  df.head().print()


  return (
    <div className="App">
      <header className="App-header">
        <a
          className="App-link"
          href="https://danfo.jsdata.org/getting-started"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn Danfojs 
        </a>
      </header>
    </div>
  );
}

export default App;

```
